backup:
  start: "§9§l[AutoSave]§f §aStarting backup of world '%world%'."
  done: "§9§l[AutoSave]§f §aBackup of world '%world%' completed. File saved to : "
  error: "§9§l[AutoSave]§f §cAn error occurred during backup: %error%"
  notfound: "§9§l[AutoSave]§f §cWorld '%world%' not found."
  usage: "§9§l[AutoSave]§f §cUsage: /backupworld <worldname>"

nopermission: "§9§l[AutoSave]§f §cYou do not have permission to use this command."

saved:
  done: "§9§l[AutoSave]§f §aWorld save completed."
  start: "§9§l[AutoSave]§f Starting auto-save every %interval% seconds."
  stop: "§9§l[AutoSave]§f Auto-save stopped."
  usage: "§9§l[AutoSave]§f §cUsage: /autosavereload" # not used

reload:
  done: "§9§l[AutoSave]§f §aConfiguration successfully reloaded."
