name: AutoSavePlugin
main: world.wltp.Main
version: 1.1
api-version: 1.21
author: WLTP
website: https://www.wltp.world/
description: Allows automatic saving or backup at desired intervals

commands:
  autosave:
    description: Reload the auto-save configuration
    usage: /autosave
    permission: autosave.use

permissions:
  autosave.use:
    description: Permission to reload auto-save configuration
    default: op
