name: AutoSavePlugin
main: world.wltp.Main
version: 1.0
api-version: 1.21
author: WLTP
website: https://www.wltp.world/
description: 원하는 시간마다 저장을 할 수 있습니다 또는 백업 가능합니다

commands:
  autosave:
    description: 자동 저장 설정 다시 불러오기
    usage: /autosave
    permission: autosave.use

  backupworld:
    description: 월드 백업 명령어
    usage: /backupworld <월드이름>
    permission: autosave.backup

permissions:
  autosave.use:
    description: 자동 저장 설정 리로드 권한
    default: op

  autosave.backup:
    description: 월드 백업 권한
    default: op
